### ISSUE TITLE
[EPG] Add age rating description and genre

### ISSUE THREAD

**Issue by DimitarCC** [opendreambox/enigma2#3]
Hello can you add in the EPG information about age rating and program genre?
It is useful for setup a parental control based on the program age rating transmitted with EPG.
Almost all German providers provide such an information in EPG.
I am using DreamOS with Enigma 4.3 if that matters.

**Comment by DimitarCC** [comment]
Is someone looking or care for user requests here?

**Comment by DimitarCC** [comment]
I guess nobody care! What a shame :(

**Comment by sreichholf** [comment]
Sorry, we didn't answer.
Gotta discuss that in the team. :)

**Comment by DimitarCC** [comment]
Thanks. It is good that you answered. I hope if this going to be added to be done in all images version - 2.5 and 2.6 because i have DM920UHD which use 2.5 image (enigma 4.3).
Thanks again i will look forward to info about this.

**Comment by DimitarCC** [comment]
Is there any news about this? Is it discussed or considered it for future? Thanks for the info in advance!

**Comment by sreichholf** [comment]
It'll take bit to implement this.
It's not just "reading the descriptor".
It also requires the epgcache to be adjusted.

**Comment by DimitarCC** [comment]
It is important this to be in works. I am aware that will take some time.

**Comment by DimitarCC** [comment]
Sorry if i am pushy but almost a year since that ticket has been opened and 4 months after the last comment....
How is the things going? Is that in the works or is not even started? or what is the progress if started? ;)

**Comment by DimitarCC** [comment]
Well if you not plan to work on this or give us any information just close that issue so to be clear that is not intended to be done. Now in my opinion you are not interested in supporting your clients. Which is kind of shame :(

**Comment by sreichholf** [comment]
This is delayed but not abandoned! I'm sorry it takes forever, but currently that's unfortunately how it is.

**Comment by DimitarCC** [comment]
Ok. Thanks for the info. I hope if it is done to be available also for DM920

**Comment by DimitarCC** [comment]
I am sorry to say it but that issue has been opened 2 years ago. A year ago it is said that it is not abandoned but for me the whole thing seems dead. No offence but its not serious to have no movement on this for 2 years. And i whole year without single update on this.
I dont know what is going on. But if you cant support this make it opensource so someone like us to be able to support it.
DM920 is very good STB and still actual at the moment but its software is kind of out of date and buggy and nobody do anything about it.
I am really sorry that i have to say this but for me this is dead and i dont expect anything in this to happen. 
So i close this issue. Its pointless.
